/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sqq_updateapk_PatchUtils */

#ifndef _Included_com_sqq_updateapk_PatchUtils
#define _Included_com_sqq_updateapk_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sqq_updateapk_PatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sqq_updateapk_PatchUtils_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
